### PR TITLE
Use Github markdown

### PR DESCRIPTION
**Pull request by gchauvet**
This is my first small contribution to the Gobo Eiffel project with 2 (small) changes :

1) I used  Github markdown on Readme.txt, renamed to README.md;
2) According to a previous issue about geant tool, I applied the relative path annotation in misc/eiffel.eant file

### CODE REVIEW

**Comment by ebezault** [comment]
I don't really share your point of view that `ET_C_GENERATOR` is too much specific to gec. The goal of the Eiffel Tools library is to make the code of gec available for reuse by other projects. And I do not see why it would not be the case for this class. Gec is a command-line compiler. But we could imagine another project gestudio which would be an IDE similar to EiffelStudio. This graphical tool would reuse the code of gec which has been made available in the Eiffel Tools library, including this class `ET_C_GENERATOR` when one click on the Compile button.

As for moving .gitignore out of the "bin" directory, let me explain why I did it the way it is. First, I want the "bin" directory to appear (even empty) when we check-out code from the repository. The fact that we have the .gitignore file in this directory does the trick. Second, it happened in the past that there was some file in this directory which needed to be committed. And it might well happen in the future (who knows). That's why I prefer to explicitly declare the list of files which I want to exclude rather than having a general (albeit simplier) file which ignores everything. That way if a file which was not initially listed in the .gitgnore file finds its way in the "bin" directory, it will raise my attention and I will be able to decide whether I want to add it to the repository or add it to the ignore list.

**Comment by gchauvet** [comment]
Okay I've reseted changes except for eiffel.eant.
I will change the description of this pull request ASAP.

**Comment by gchauvet** [comment]
Adding a .gitattributes file to ignore the C generated code from language statistics

**Comment by ebezault** [comment]
Can you explain more about this "linguist" option? Is it specific to GitHub to determine the percentage of languages used in the project, or is it more general than GitHub?
In any case, it will be nice to see the Gobo project listed as an Eiffel project and not as a C project.

**Comment by gchauvet** [comment]
Yes, if you go to https://github.com/gchauvet?tab=repositories
you can see gobo as an Eiffel language project instead of C project.

For linguist option, please fellow this link : https://github.com/github/linguist
This library is used by github to detect & create statistics about languages used in each projects

**Comment by ebezault** [comment]
Is there a way to perform a "fast-forward" merge when we click on the Merge button in GitHub Web page?
For example, for this pull request, it created a new commit node which was not really needed (if just repeats what has been done in the branch, and it is marked as committed by me).
If not, next time a fast-forward is possible, I might process the pull request from my local repo to avoid this extra commit. Unless someone see some benefit in having this extra commit...

**Comment by gchauvet** [comment]
From what I know about the online merging process on Github, this is not possible :/
I will take into account your remark about for my futures pull requests if I need to modify some files whose effects are only visible online.

**Comment by ebezault** [comment]
Perhaps it's a good thing to have an extra commit node for the merge. That way we see the intermediate commits which led to the code to be merged. Otherwise, this intermediary commits end up in the master branch and we don't clearly see when the work which led to the top of the master branch really started.

Thank you for the link to 'linguist'. I will have a look at it.
And another thank you for having made Gobo visible as an Eiffel project on GitHub.

**Pull request merged**
