### PR TITLE
Fix ut uri assertion errors

### PR DESCRIPTION
**Pull request by berenddeboer**
This should fix them. But before you commit, can I update travis so it compiles and tests the suite with ISE in debug mode? That way I would have found this earlier.

### CODE REVIEW

**Comment by ebezault** [comment]
When I put travis in place, I tried to have it set up for ISE as well. But travis aborts because compiling with ISE is way too slow.

**Comment by ebezault** [comment]
It's still failing:

> Test Results:
> ABORT:  [UT_TEST_URI_RESOLVE.test_normal_cases] Eiffel exception
> -------------------------------------------------------------------------------
> Class / Object      Routine                Nature of exception           Effect
> -------------------------------------------------------------------------------
> UT_URI              _invariant @3          query_items_if_query:
> <000002AA4378A038>                         Class invariant violated.     Fail
> -------------------------------------------------------------------------------
> UT_URI              _invariant
> <000002AA4378A038>                         Routine failure.              Fail
> -------------------------------------------------------------------------------
> UT_URI              make_resolve @10
> <000002AA4378A038>                         Routine failure.              Fail
> -------------------------------------------------------------------------------
> UT_TEST_URI_RESOLVE test_normal_cases @18
> <000002AA4376CDA8>                         Routine failure.              Fail
> -------------------------------------------------------------------------------
> PROCEDURE           fast_call
> <000002AA4376CE28>                         Routine failure.              Fail
> -------------------------------------------------------------------------------
> PROCEDURE           call @3
> <000002AA4376CE28>                         Routine failure.              Fail
> -------------------------------------------------------------------------------
> UT_TEST_URI_RESOLVE execute_without_rescue @4
> <000002AA4376CDA8>  (From TS_TEST_CASE)    Routine failure.              Fail
> -------------------------------------------------------------------------------
> UT_TEST_URI_RESOLVE execute_with_rescue @3
> <000002AA4376CDA8>  (From TS_TEST_CASE)    Routine failure.              Fail
> -------------------------------------------------------------------------------
> UT_TEST_URI_RESOLVE execute @10
> <000002AA4376CDA8>  (From TS_TEST_CASE)    Routine failure.              Fail
> -------------------------------------------------------------------------------
> TS_TEST_SUITE       execute @5
> <000002AA4376C5B8>                         Routine failure.              Fail
> -------------------------------------------------------------------------------
> XURI                execute_with_summary @44
> <000002AA4376A588>  (From TS_TESTER)       Routine failure.              Fail
> -------------------------------------------------------------------------------
> XURI                execute_with_output @10
> <000002AA4376A588>  (From TS_TESTER)       Routine failure.              Fail
> -------------------------------------------------------------------------------
> XURI                execute @9
> <000002AA4376A588>  (From TS_TESTER)       Routine failure.              Fail
> -------------------------------------------------------------------------------
> XURI                make @5
> <000002AA4376A588>  (From TS_TESTER)       Routine failure.              Fail
> -------------------------------------------------------------------------------
> XURI                root's creation
> <000002AA4376A588>                         Routine failure.              Exit
> -------------------------------------------------------------------------------
> 
> ABORT:  [UT_TEST_URI_RESOLVE.test_abnormal_cases] Eiffel exception
> -------------------------------------------------------------------------------
> Class / Object      Routine                Nature of exception           Effect
> -------------------------------------------------------------------------------
> UT_URI              _invariant @3          query_items_if_query:
> <000002AA4378D438>                         Class invariant violated.     Fail
> -------------------------------------------------------------------------------
> UT_URI              _invariant
> <000002AA4378D438>                         Routine failure.              Fail
> -------------------------------------------------------------------------------
> UT_URI              make_resolve @10
> <000002AA4378D438>                         Routine failure.              Fail
> -------------------------------------------------------------------------------
> UT_TEST_URI_RESOLVE test_abnormal_cases @2
> <000002AA4376D0A8>                         Routine failure.              Fail
> -------------------------------------------------------------------------------
> PROCEDURE           fast_call
> <000002AA4376D128>                         Routine failure.              Fail
> -------------------------------------------------------------------------------
> PROCEDURE           call @3
> <000002AA4376D128>                         Routine failure.              Fail
> -------------------------------------------------------------------------------
> UT_TEST_URI_RESOLVE execute_without_rescue @4
> <000002AA4376D0A8>  (From TS_TEST_CASE)    Routine failure.              Fail
> -------------------------------------------------------------------------------
> UT_TEST_URI_RESOLVE execute_with_rescue @3
> <000002AA4376D0A8>  (From TS_TEST_CASE)    Routine failure.              Fail
> -------------------------------------------------------------------------------
> UT_TEST_URI_RESOLVE execute @10
> <000002AA4376D0A8>  (From TS_TEST_CASE)    Routine failure.              Fail
> -------------------------------------------------------------------------------
> TS_TEST_SUITE       execute @5
> <000002AA4376C5B8>                         Routine failure.              Fail
> -------------------------------------------------------------------------------
> XURI                execute_with_summary @44
> <000002AA4376A588>  (From TS_TESTER)       Routine failure.              Fail
> -------------------------------------------------------------------------------
> XURI                execute_with_output @10
> <000002AA4376A588>  (From TS_TESTER)       Routine failure.              Fail
> -------------------------------------------------------------------------------
> XURI                execute @9
> <000002AA4376A588>  (From TS_TESTER)       Routine failure.              Fail
> -------------------------------------------------------------------------------
> XURI                make @5
> <000002AA4376A588>  (From TS_TESTER)       Routine failure.              Fail
> -------------------------------------------------------------------------------
> XURI                root's creation
> <000002AA4376A588>                         Routine failure.              Exit
> -------------------------------------------------------------------------------

**Comment by ebezault** [comment]
I'm almost done cutting the test suite into smaller chunks so that they are not too long (less than 50 minutes as per Travis limitation) when using ISE. In the meantime, here is what we get for the failing test:

https://travis-ci.org/ebezault/gobo/jobs/439697372

**Comment by berenddeboer** [comment]
Should work now, I inadvertedly only tested the first test class instead of all classes here.

**Comment by ebezault** [comment]
Yes, it works.
Thanks.

**Comment by ebezault** [comment]
In fact there are still some tests failing:

https://travis-ci.org/ebezault/gobo/jobs/440050586

**Comment by berenddeboer** [comment]
Pushed one more fix. If there is an issue pulling this in let me know, and I can create a new branch.

**Pull request merged**
